global:
  repository: 172.16.5.67
  project: redis
image: redis-sentinel-operator
tag: v4.1.1
pullPolicy: IfNotPresent
containerName: redisoperator
podAnnotations: {}
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 200Mi
rbac:
  install: true
  apiVersion: v1
  imagePullSecrets: []
monitoring:
  enabled: false
  serviceMonitor: false
  serviceAnnotations: {}
  prometheus:
    name: unknown
