global:
  repository: 172.16.5.67
  project: redis
image: redis-sentinel-operator
tag: v4.3.8
pullPolicy: IfNotPresent
containerName: redisoperator
backupContainerName: redisbackupoperator

fullname: redis-sentinel-operator

backupimage: redis-backup-operator

redis5image: redis

redis6image: redis

sidecarimage: s3cmd

exporterimage: exporter

podAnnotations: {}

resources:
  requests:
    cpu: 2
    memory: 2Gi
  limits:
    cpu: 4
    memory: 4Gi

rbac:
  install: true
  apiVersion: v1
  imagePullSecrets: []

monitoring:
  enabled: false
  serviceMonitor: false
  serviceAnnotations: {}
  prometheus:
    name: unknown

xc:
  enable: true
