name: Redis Sentinel Controllers
description: Redis Sentinel集群部署及管理模块
single: true
chartName: redis-sentinel-controllers
appType: redis-sentinel
packageType: controller
version: 0.0.0
dependOn:
upgradeOn: