name: Redis Sentinel Controllers
description: Redis Sentinel集群部署及管理模块
single: true
chartName: redis-sentinel-controllers
appType: redis-sentinel
packageType: controller
version: 0.0.1
dependOn:
  - name: redis-sentinel-crds
    version: 0.0.1
upgradeOn:
  - name: redis-sentinel-controllers
    version: 0.0.0
