apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  labels:
    app.kubernetes.io/component: app
{{ include "helm-labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: app
{{ include "common-labels" . | indent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
{{ include "common-labels" . | indent 8 }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
{{- if .Values.rbac.install }}
      serviceAccountName: {{ include "name" . | quote }}
{{- end }}
      containers:
      - name: "{{ .Values.containerName }}"
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        env:
          - name: backup_image
            value: {{ .Values.sidecarimage }}
          - name: redis5_image
            value: {{ .Values.redis5image }}
          - name: redis6_image
            value: {{ .Values.redis6image }}
          - name: exporter_image
            value: {{ .Values.exporterimage }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 9710
          name: metrics
          protocol: TCP
      - name: "{{ .Values.backupContainerName }}"
        image: {{ .Values.backupimage }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        env:
          - name: backup_image
            value: {{ .Values.sidecarimage }}
          - name: redis5_image
            value: {{ .Values.redis5image }}
          - name: redis6_image
            value: {{ .Values.redis6image }}
          - name: exporter_image
            value: {{ .Values.exporterimage }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
